In [13]:
import pandas as pd
df = pd.read_csv("../datasets/simulation_dataset.csv")
print(df.shape)
df.head()

(26309, 30)

,Timestamp,SoC,SoH,Battery_Voltage,Battery_Current,Battery_Temperature,Charge_Cycles,Motor_Temperature,Motor_Vibration,Motor_Torque,...,Load_Weight,Driving_Speed,Distance_Traveled,Idle_Time,Route_Roughness,RUL,Failure_Probability,Maintenance_Type,TTF,Component_Health_Score
0,2024-04-01 23:00:00,0.881918,0.594962,362.809211,-107.132101,26.531187,582.151378,59.692655,0.232854,140.661327,...,592.522959,58.899818,96.738708,0.351316,0.284129,223.400321,0,3,106.027278,0.926594
1,2024-04-01 23:15:00,0.842283,0.913706,366.830017,-17.909172,25.080270,116.705122,58.130642,0.258170,188.806254,...,908.232090,47.601883,1.996796,0.619714,0.830869,282.356324,0,3,146.569368,0.879687
2,2024-04-01 23:30:00,0.812015,0.939819,358.105357,-12.700803,27.054168,169.602803,48.317422,1.803575,142.159528,...,942.313074,42.399131,3.003446,6.029300,0.922292,209.879002,0,1,164.781559,0.949694
3,2024-04-01 23:45:00,0.861919,0.933208,357.150815,-34.398991,31.029168,125.607724,46.034486,0.222447,324.579749,...,601.350671,42.925547,94.769432,0.801428,0.102990,210.273101,0,0,112.480674,0.036096
4,2024-04-02 00:00:00,0.987063,0.988339,363.333079,-32.396753,58.690601,134.269162,48.278553,1.760410,125.836560,...,960.716365,56.771225,3.448081,0.723454,0.219352,292.353195,0,0,157.331716,0.720801

In [14]:
df.drop(["RUL","Failure_Probability","TTF","Component_Health_Score","Maintenance_Type"],axis=1,inplace=True)

In [15]:
df.head()

,Timestamp,SoC,SoH,Battery_Voltage,Battery_Current,Battery_Temperature,Charge_Cycles,Motor_Temperature,Motor_Vibration,Motor_Torque,...,Tire_Pressure,Tire_Temperature,Suspension_Load,Ambient_Temperature,Ambient_Humidity,Load_Weight,Driving_Speed,Distance_Traveled,Idle_Time,Route_Roughness
0,2024-04-01 23:00:00,0.881918,0.594962,362.809211,-107.132101,26.531187,582.151378,59.692655,0.232854,140.661327,...,30.868960,27.348099,183.458490,18.543364,83.157294,592.522959,58.899818,96.738708,0.351316,0.284129
1,2024-04-01 23:15:00,0.842283,0.913706,366.830017,-17.909172,25.080270,116.705122,58.130642,0.258170,188.806254,...,34.101115,34.575678,187.594260,21.050078,43.801977,908.232090,47.601883,1.996796,0.619714,0.830869
2,2024-04-01 23:30:00,0.812015,0.939819,358.105357,-12.700803,27.054168,169.602803,48.317422,1.803575,142.159528,...,23.647516,25.259583,491.484602,12.008503,45.265928,942.313074,42.399131,3.003446,6.029300,0.922292
3,2024-04-01 23:45:00,0.861919,0.933208,357.150815,-34.398991,31.029168,125.607724,46.034486,0.222447,324.579749,...,30.395930,28.209872,172.439817,19.676410,39.642159,601.350671,42.925547,94.769432,0.801428,0.102990
4,2024-04-02 00:00:00,0.987063,0.988339,363.333079,-32.396753,58.690601,134.269162,48.278553,1.760410,125.836560,...,32.170194,26.297317,141.820033,23.184187,30.715581,960.716365,56.771225,3.448081,0.723454,0.219352

### Renaming Important Columns owing to the Database convention

In [16]:
df = df.rename(columns={
    "Timestamp": "timestamp",

    "SoC": "soc",
    "SoH": "soh",

    "Battery_Voltage": "battery_voltage",
    "Battery_Current": "battery_current",
    "Battery_Temperature": "battery_temperature",

    "Charge_Cycles": "charge_cycles",

    "Motor_Temperature": "motor_temperature",
    "Motor_Vibration": "motor_vibration",
    "Motor_Torque": "motor_torque",
    "Motor_RPM": "motor_rpm",

    "Power_Consumption": "power_consumption",

    "Brake_Pad_Wear": "brake_pad_wear",
    "Brake_Pressure": "brake_pressure",
    "Reg_Brake_Efficiency": "reg_brake_efficiency",

    "Tire_Pressure": "tire_pressure",
    "Tire_Temperature": "tire_temperature",

    "Suspension_Load": "suspension_load",

    "Ambient_Temperature": "ambient_temperature",
    "Ambient_Humidity": "ambient_humidity",

    "Load_Weight": "load_weight",

    "Driving_Speed": "driving_speed",
    "Distance_Traveled": "distance_traveled",

    "Idle_Time": "idle_time",

    "Route_Roughness": "route_roughness"
})

In [17]:
df.head()

,timestamp,soc,soh,battery_voltage,battery_current,battery_temperature,charge_cycles,motor_temperature,motor_vibration,motor_torque,...,tire_pressure,tire_temperature,suspension_load,ambient_temperature,ambient_humidity,load_weight,driving_speed,distance_traveled,idle_time,route_roughness
0,2024-04-01 23:00:00,0.881918,0.594962,362.809211,-107.132101,26.531187,582.151378,59.692655,0.232854,140.661327,...,30.868960,27.348099,183.458490,18.543364,83.157294,592.522959,58.899818,96.738708,0.351316,0.284129
1,2024-04-01 23:15:00,0.842283,0.913706,366.830017,-17.909172,25.080270,116.705122,58.130642,0.258170,188.806254,...,34.101115,34.575678,187.594260,21.050078,43.801977,908.232090,47.601883,1.996796,0.619714,0.830869
2,2024-04-01 23:30:00,0.812015,0.939819,358.105357,-12.700803,27.054168,169.602803,48.317422,1.803575,142.159528,...,23.647516,25.259583,491.484602,12.008503,45.265928,942.313074,42.399131,3.003446,6.029300,0.922292
3,2024-04-01 23:45:00,0.861919,0.933208,357.150815,-34.398991,31.029168,125.607724,46.034486,0.222447,324.579749,...,30.395930,28.209872,172.439817,19.676410,39.642159,601.350671,42.925547,94.769432,0.801428,0.102990
4,2024-04-02 00:00:00,0.987063,0.988339,363.333079,-32.396753,58.690601,134.269162,48.278553,1.760410,125.836560,...,32.170194,26.297317,141.820033,23.184187,30.715581,960.716365,56.771225,3.448081,0.723454,0.219352

In [18]:
num_vehicles = 6
chunk_size = len(df) // num_vehicles

chunk_size

4384

In [19]:
vehicle_names = [
    "EV_101",
    "EV_102",
    "EV_201",
    "EV_301",
    "EV_302",
    "EV_303"
]

for i, vehicle in enumerate(vehicle_names):

    start = i * chunk_size

    if i == len(vehicle_names) - 1:
        end = len(df)
    else:
        end = (i + 1) * chunk_size

    chunk = df.iloc[start:end]

    chunk.to_csv(
        f"../datasets/EV_simulated_chunks/{vehicle}.csv",
        index=False
    )

    print(vehicle, chunk.shape)

EV_101 (4384, 25)
EV_102 (4384, 25)
EV_201 (4384, 25)
EV_301 (4384, 25)
EV_302 (4384, 25)
EV_303 (4389, 25)