In [6]:
import pandas as pd
df = pd.read_csv("../datasets/EV_Predictive_Maintenance_Dataset_15min.csv")

In [7]:
df.head()

,Timestamp,SoC,SoH,Battery_Voltage,Battery_Current,Battery_Temperature,Charge_Cycles,Motor_Temperature,Motor_Vibration,Motor_Torque,...,Load_Weight,Driving_Speed,Distance_Traveled,Idle_Time,Route_Roughness,RUL,Failure_Probability,Maintenance_Type,TTF,Component_Health_Score
0,2020-01-01 00:00:00,0.826099,0.941338,210.163881,-22.753095,27.149201,149.190930,48.496049,0.369095,113.435589,...,741.754518,103.421162,66.232383,0.520922,0.225970,260.503381,0,1,111.116697,0.852745
1,2020-01-01 00:15:00,0.064728,0.916059,364.000102,-27.701120,53.655101,171.702388,57.829492,1.449195,105.587160,...,769.134035,46.041935,3.146238,0.844005,0.204350,212.813954,0,2,179.229425,0.827616
2,2020-01-01 00:30:00,0.873643,0.908020,388.855089,-36.646406,29.559090,191.617645,46.518363,1.859045,119.610302,...,917.262931,59.588422,79.909148,0.992405,0.175125,273.394511,0,1,171.852663,0.876887
3,2020-01-01 00:45:00,0.853009,0.916476,370.570602,-37.609429,29.690283,111.881817,54.163681,0.381500,182.535625,...,600.598736,44.222285,0.774000,0.007615,0.213264,229.508442,0,0,165.221328,0.816290
4,2020-01-01 01:00:00,0.947540,0.913206,390.011904,-14.275808,28.864338,163.774377,42.075978,0.433927,173.298044,...,613.153029,41.374684,2.872124,0.771938,0.770257,257.302631,1,0,176.890659,0.744260

In [9]:
df.tail()

,Timestamp,SoC,SoH,Battery_Voltage,Battery_Current,Battery_Temperature,Charge_Cycles,Motor_Temperature,Motor_Vibration,Motor_Torque,...,Load_Weight,Driving_Speed,Distance_Traveled,Idle_Time,Route_Roughness,RUL,Failure_Probability,Maintenance_Type,TTF,Component_Health_Score
175388,2024-12-31 23:00:00,0.138233,0.431120,384.116305,-129.315900,29.849594,146.407798,56.851517,0.220966,111.248321,...,562.653005,57.306500,6.806604,0.671829,0.280922,252.165475,0,2,155.122316,0.026428
175389,2024-12-31 23:15:00,0.007051,0.471936,368.879319,-19.750505,27.876339,137.981542,58.729215,0.403436,181.982436,...,817.911222,117.607066,7.185362,0.177174,0.192911,230.284883,0,1,136.754597,0.257027
175390,2024-12-31 23:30:00,0.911666,0.948819,398.791778,-23.695062,29.149039,167.508177,55.096363,0.332669,169.563143,...,910.771928,41.110987,6.401346,0.756041,0.217087,242.494039,0,2,168.009195,0.752161
175391,2024-12-31 23:45:00,0.845654,0.939871,213.638423,-19.382220,25.868638,130.470338,52.823655,0.415336,159.408019,...,569.399279,41.227741,3.933113,0.005801,0.202259,262.523879,0,0,101.886011,0.917954
175392,2025-01-01 00:00:00,0.899133,0.926500,377.148624,-38.039942,34.464870,166.089326,56.440559,0.227774,133.061207,...,714.031263,111.014935,5.550868,9.108571,0.224439,294.147392,0,0,199.800807,0.906651

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 175393 entries, 0 to 175392
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Timestamp               175393 non-null  str
 1   SoC                     175393 non-null  float64
 2   SoH                     175393 non-null  float64
 3   Battery_Voltage         175393 non-null  float64
 4   Battery_Current         175393 non-null  float64
 5   Battery_Temperature     175393 non-null  float64
 6   Charge_Cycles           175393 non-null  float64
 7   Motor_Temperature       175393 non-null  float64
 8   Motor_Vibration         175393 non-null  float64
 9   Motor_Torque            175393 non-null  float64
 10  Motor_RPM               175393 non-null  float64
 11  Power_Consumption       175393 non-null  float64
 12  Brake_Pad_Wear          175393 non-null  float64
 13  Brake_Pressure          175393 non-null  float64
 14  Reg_Brake_Efficiency    175393 non-null  float64
 15  Tire_Pressure           175393 non-null  float64
 16  Tire_Temperature        175393 non-null  float64
 17  Suspension_Load         175393 non-null  float64
 18  Ambient_Temperature     175393 non-null  float64
 19  Ambient_Humidity        175393 non-null  float64
 20  Load_Weight             175393 non-null  float64
 21  Driving_Speed           175393 non-null  float64
 22  Distance_Traveled       175393 non-null  float64
 23  Idle_Time               175393 non-null  float64
 24  Route_Roughness         175393 non-null  float64
 25  RUL                     175393 non-null  float64
 26  Failure_Probability     175393 non-null  int64
 27  Maintenance_Type        175393 non-null  int64
 28  TTF                     175393 non-null  float64
 29  Component_Health_Score  175393 non-null  float64
dtypes: float64(27), int64(2), str(1)
memory usage: 40.1 MB

In [11]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

df = df.sort_values("Timestamp")

df.reset_index(drop=True, inplace=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 175393 entries, 0 to 175392
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Timestamp               175393 non-null  datetime64[us]
 1   SoC                     175393 non-null  float64
 2   SoH                     175393 non-null  float64
 3   Battery_Voltage         175393 non-null  float64
 4   Battery_Current         175393 non-null  float64
 5   Battery_Temperature     175393 non-null  float64
 6   Charge_Cycles           175393 non-null  float64
 7   Motor_Temperature       175393 non-null  float64
 8   Motor_Vibration         175393 non-null  float64
 9   Motor_Torque            175393 non-null  float64
 10  Motor_RPM               175393 non-null  float64
 11  Power_Consumption       175393 non-null  float64
 12  Brake_Pad_Wear          175393 non-null  float64
 13  Brake_Pressure          175393 non-null  float64
 14  Reg_Brake_Efficiency    175393 non-null  float64
 15  Tire_Pressure           175393 non-null  float64
 16  Tire_Temperature        175393 non-null  float64
 17  Suspension_Load         175393 non-null  float64
 18  Ambient_Temperature     175393 non-null  float64
 19  Ambient_Humidity        175393 non-null  float64
 20  Load_Weight             175393 non-null  float64
 21  Driving_Speed           175393 non-null  float64
 22  Distance_Traveled       175393 non-null  float64
 23  Idle_Time               175393 non-null  float64
 24  Route_Roughness         175393 non-null  float64
 25  RUL                     175393 non-null  float64
 26  Failure_Probability     175393 non-null  int64
 27  Maintenance_Type        175393 non-null  int64
 28  TTF                     175393 non-null  float64
 29  Component_Health_Score  175393 non-null  float64
dtypes: datetime64[us](1), float64(27), int64(2)
memory usage: 40.1 MB

In [14]:
split_idx = int(len(df) * 0.85)

train_df = df.iloc[:split_idx]

simulation_df = df.iloc[split_idx:]

In [15]:
print(train_df.shape)
print(simulation_df.shape)

(149084, 30)
(26309, 30)

In [16]:
train_df.to_csv(
    "../datasets/EVProject_dataset.csv",
    index=False
)

simulation_df.to_csv(
    "../datasets/simulation_dataset.csv",
    index=False
)

In [17]:
simulation_df.head()

,Timestamp,SoC,SoH,Battery_Voltage,Battery_Current,Battery_Temperature,Charge_Cycles,Motor_Temperature,Motor_Vibration,Motor_Torque,...,Load_Weight,Driving_Speed,Distance_Traveled,Idle_Time,Route_Roughness,RUL,Failure_Probability,Maintenance_Type,TTF,Component_Health_Score
149084,2024-04-01 23:00:00,0.881918,0.594962,362.809211,-107.132101,26.531187,582.151378,59.692655,0.232854,140.661327,...,592.522959,58.899818,96.738708,0.351316,0.284129,223.400321,0,3,106.027278,0.926594
149085,2024-04-01 23:15:00,0.842283,0.913706,366.830017,-17.909172,25.080270,116.705122,58.130642,0.258170,188.806254,...,908.232090,47.601883,1.996796,0.619714,0.830869,282.356324,0,3,146.569368,0.879687
149086,2024-04-01 23:30:00,0.812015,0.939819,358.105357,-12.700803,27.054168,169.602803,48.317422,1.803575,142.159528,...,942.313074,42.399131,3.003446,6.029300,0.922292,209.879002,0,1,164.781559,0.949694
149087,2024-04-01 23:45:00,0.861919,0.933208,357.150815,-34.398991,31.029168,125.607724,46.034486,0.222447,324.579749,...,601.350671,42.925547,94.769432,0.801428,0.102990,210.273101,0,0,112.480674,0.036096
149088,2024-04-02 00:00:00,0.987063,0.988339,363.333079,-32.396753,58.690601,134.269162,48.278553,1.760410,125.836560,...,960.716365,56.771225,3.448081,0.723454,0.219352,292.353195,0,0,157.331716,0.720801